### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by CalebEverett** [google-developer-training/basic-android-kotlin-compose-training-unscramble#1]
Second block of code in codelab step 7 references property that does not exist in state

[7. Verify guess word and update score](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#6)

```kotlin
import kotlinx.coroutines.flow.update

   if (_uiState.value.userGuess.equals(currentWord, true)) {
   } else {
       // User's guess is wrong, show an error
       _uiState.update { currentState ->
           currentState.copy(isGuessedWordWrong = true)
       }
   }
```

Here is the code in the solution:

```kotlin
    fun checkUserGuess() {
        if (userGuess.equals(currentWord, ignoreCase = true)) {
            // User's guess is correct, increase the score
            // and call updateGameState() to prepare the game for next round
            val updatedScore = _uiState.value.score.plus(SCORE_INCREASE)
            updateGameState(updatedScore)
        } else {
            // User's guess is wrong, show an error
            _uiState.update { currentState ->
                currentState.copy(isGuessedWordWrong = true)
            }
        }
        // Reset user guess
        updateUserGuess("")
    }
```

**Comment by mattiasjback** [comment]
This is still an issue. Very confusing.

**Comment by AlanDerich** [comment]
I noticed the same. It got me confused for a while.

**Comment by kofi-k** [comment]
Aaah, here I thought I wasn't doing something right

**Comment by osuleymanova** [comment]
Hello @CalebEverett,

Thank you for reaching out and reporting this issue. The code snippet in the section 7 was fixed:

 
![Screen Shot 2022-11-23 at 11 17 41 AM](https://user-images.githubusercontent.com/86437155/203629998-592bf7d3-dd5a-4364-b00e-8e53e85f6993.png)

Our apologies for the confusion it caused. Happy coding!
