### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by EzeGmnz** [google-developer-training/basic-android-kotlin-compose-training-unscramble#109]
### Url of the codelab

[CodeLab](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#2)

### Description 

Just a minor mistake on the comment in this code snippet for the `FinalScoreDialog`. It mentions this tip:
```
// Dismiss the dialog when the user clicks outside the dialog or on the back
// button. If you want to disable that functionality, simply use an empty
// onCloseRequest.
```

instead, it should be

```
// Dismiss the dialog when the user clicks outside the dialog or on the back
// button. If you want to disable that functionality, simply use an empty
// onDismissRequest.
```

note the `onDismissRequest`, as this is the correct parameter

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/40328394/98e4ac58-f90d-48c4-83fd-5e9f397b3ed4)

Hope this helps!

Regards

**Comment by osuleymanova** [comment]
Hello @EzeGmnz,

Thank you for reaching out to us. The typo is fixed and will be published soon.
