### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by AlanDerich** [google-developer-training/basic-android-kotlin-compose-training-unscramble#11]
![Write unit tests for ViewModel - Google Chrome 31_10_2022 11_58_18](https://user-images.githubusercontent.com/50056881/198970878-d865b8ab-cb3c-44b1-ba25-7efb6ccb76c5.jpg)
The highlighted step should be 1. Create a gameViewModel_AllWordsGuessed_UiStateUpdatedCorrectly()

**Comment by osuleymanova** [comment]
Hello @AlanDerich,
Thank you for reaching out to us and reporting this issue. It is fixed:

![Screen Shot 2022-11-23 at 9 22 15 AM](https://user-images.githubusercontent.com/86437155/203621247-170d0df8-e4f5-4fc3-b585-01cccb1ef22c.png)
