### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by SergioTellezSanchez** [google-developer-training/basic-android-kotlin-compose-training-unscramble#20]
isGuessWrong parameter is not being added to the GameLayout call in the example

GameLayout(
   currentScrambledWord = gameUiState.currentScrambledWord,
**isGuessWrong = gameUiState.isGuessedWordWrong,**
   userGuess = gameViewModel.userGuess,
   onUserGuessChanged = { gameViewModel.updateUserGuess(it) },
   onKeyboardDone = { gameViewModel.checkUserGuess() },
  
)

**Comment by osuleymanova** [comment]
Hello @SergioTellezSanchez,

Thanks for reaching out to us. The code snippet is updated with the parameter added:


![Screen Shot 2022-12-09 at 2 11 35 PM](https://user-images.githubusercontent.com/86437155/206804544-e1b02ff9-2195-40be-840a-0a2351e6048a.png)
