### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/basic-android-kotlin-compose-training-unscramble#28]
Step 7 (Verify guess word and update score):
After sub-step 3 there should be another sub-step before sub-step 4 as follows:

Pass the `gameUiState.isGuessedWordWrong` to the `GameLayout()` composable.

```kotlin
GameLayout(
   currentScrambledWord = gameUiState.currentScrambledWord,
   userGuess = gameViewModel.userGuess,
   onUserGuessChanged = { gameViewModel.updateUserGuess(it) },
   onKeyboardDone = { gameViewModel.checkUserGuess() },
   isGuessWrong = gameUiState.isGuessedWordWrong
)

**Comment by osuleymanova** [comment]
Hello @hassan0599,

Thanks for reaching out. Per your request we updated the steps:

![Screen Shot 2022-12-14 at 10 56 21 AM](https://user-images.githubusercontent.com/86437155/207689549-497f95ef-2cd7-418b-84a2-d8272c7b317d.png)
