### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by ravisharmas2013** [google-developer-training/basic-android-kotlin-compose-training-unscramble#36]
Serial 3 below is a bit confusion.

3. In the GameLayout() composable function, add lambda parameters for onUserGuessChanged and onKeyboardDone.

it gives an impression that the composable function GameLayout() needs to be changed, however, it is actually taking about passing the parameters to the function call GameLayout() in the GameScreen composable.

**Comment by osuleymanova** [comment]
Hello @ravisharmas2013,

Thank you for reaching out to us and sharing your feedback. We edited the step and published. 


![Screenshot 2023-07-13 at 5 02 35 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/9dbb8fbf-9131-4840-92c0-942075fe6b86)
