### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by wngu6** [google-developer-training/basic-android-kotlin-compose-training-unscramble#38]
In section 6, in the first step under 'Display the guess word', there's a typo:
...set onUserGuessChanged to onValueChange and onKeyboardDone() to onDone keyboard action.
Correction:
...set onValueChange  to onUserGuessChanged and onDone  to onKeyboardDone() keyboard action.

**Comment by osuleymanova** [comment]
Hello @wngu6, 

Thank you for reaching out to us. The text of the instruction is fixed and published:

![Screenshot 2023-07-13 at 4 38 18 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/ba84198c-11cd-4325-bbcc-56aa8f193c53)

Happy coding!
