### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by yothio** [google-developer-training/basic-android-kotlin-compose-training-unscramble#39]
In section 9, in the fourth step under 'To implement game-end logic' , there's sample code mistake:
With the current code, `currentWordCount` would be over 10.

I would change it as follows and it should be fine

```diff
private fun updateGameState(updatedScore: Int) {
   if (usedWords.size == MAX_NO_OF_WORDS){
       //Last round in the game, update isGameOver to true, don't pick a new word
       _uiState.update { currentState ->
           currentState.copy(
               isGuessedWordWrong = false,
               score = updatedScore,
-              currentWordCount = currentState.currentWordCount.inc(),
               isGameOver = true
           )
       }
   } else{
       // Normal round in the game
       _uiState.update { currentState ->
           currentState.copy(
               isGuessedWordWrong = false,
               currentScrambledWord = pickRandomWordAndShuffle(),
               currentWordCount = currentState.currentWordCount.inc(),
               score = updatedScore
           )
       }
   }
}
```

**Comment by AAB999** [comment]
@yothio 
Yes, I just saw that too.... why counting anyway, if the game is over? :-) Maybe it solves when the next step is implemented? Let's see what ist coming...

**Comment by osuleymanova** [comment]
Hello @yothio, @AAB999,

Thank you so much for reaching out to us. This line definitely needed to be removed. The code snippet has been updated:

![Screenshot 2023-07-13 at 4 38 18 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/1a07b0e8-ef60-4148-8791-e7604de1f4a1)

Happy coding!
