### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by temp-droid** [google-developer-training/basic-android-kotlin-compose-training-unscramble#44]
Typo in the phrase: `To get the correct player guess, use the getUnscrambleWord() function,`

The method is named `getUnscrambledWord` afterwards (with an extra `d` after `unscramble`).

**Comment by osuleymanova** [comment]
Hello @temp-droid,

Thank you for reaching out to us and reporting this typo. It will be fixed and republished.

Hope you enjoy Android course.
