### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by sdboyapati** [google-developer-training/basic-android-kotlin-compose-training-unscramble#5]
@Test annotation is not recognized if testImplementation of Junit is included in dependencies.
implementation of junit should be included in  dependencies in order to annotate test methods with @Test.

**Comment by osuleymanova** [comment]
Hello @sdboyapati,

The codelab url was found. Thank you for sharing your feedback, we will consider it.
