### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by jameynakama** [google-developer-training/basic-android-kotlin-compose-training-unscramble#52]
The default values for `score` and `currentWordCount` are flip-flopped in this snippet.

"""
Next, similar to the updates for the score, you need to update the word count.

Add another variable for the count in the GameUiState. Call it currentWordCount and initialize it to 1.
"""

```kotlin
data class GameUiState(
   val currentScrambledWord: String = "",
   val currentWordCount: Int = 0, // should be 1
   val score: Int = 1, // should be 0
   val isGuessedWordWrong: Boolean = false,
)
```

**Comment by osuleymanova** [comment]
Hello @jameynakama,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)
