### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by Sloglob** [google-developer-training/basic-android-kotlin-compose-training-unscramble#54]
text says currentWordCount must be initialized with "1" but code contains currentWordCount initialization with "0" and score initialization with "1" (must be "0")
![currentWordCount](https://user-images.githubusercontent.com/98211962/217337574-067fa2fb-4563-4854-a76b-6282a4763cb8.png)

**Comment by osuleymanova** [comment]
Hello @Sloglob,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-07-13 at 4 29 11 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/a1ea7b46-41c5-41f9-87bd-a87e6a7827b0)
