### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by Rnscd** [google-developer-training/basic-android-kotlin-compose-training-unscramble#55]
https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#7

On the topic 8 and step 5, the values of "score" and "currentWordCount" are inverted in the code.

data class GameUiState(
   val currentScrambledWord: String = "",
   val currentWordCount: Int = 0,
   val score: Int = 1,
   val isGuessedWordWrong: Boolean = false,
)

score should be = 0 and currentWordCount should be = 1.

**Comment by osuleymanova** [comment]
Hello @Rnscd,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-07-13 at 4 29 11 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/6d05ce66-bd57-4620-9bbc-f4d8412e6ef2)
