### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by CodingHarang** [google-developer-training/basic-android-kotlin-compose-training-unscramble#63]
![image](https://user-images.githubusercontent.com/95116599/221582891-3edc309b-910e-426f-ad80-a9a853efb830.png)
at number 7. description, I think "In the GameLayout file" should be change to "In the GameLayout Composable" or something else

**Comment by osuleymanova** [comment]
Hello @CodingHarang,

Thank you for reaching out and reporting this typo. We updated this step:

![Screenshot 2023-05-31 at 5 04 29 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/59e76383-26f5-4718-a19d-271e94dfda7b)
