### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by absoluteheero** [google-developer-training/basic-android-kotlin-compose-training-unscramble#66]
In order for my app to work i had to move this line:

`val uiState: StateFlow<GameUiState> = _uiState.asStateFlow()`

inside:
```
 GameViewModel() {
val uiState: StateFlow<GameUiState> = _uiState.asStateFlow()
}
```

**Comment by osuleymanova** [comment]
Hello @absoluteheero,

Thank you for reaching out to us. 
That's correct, as instructed in the codelab:
 
![Screenshot 2023-07-13 at 4 07 35 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/e2b10947-c830-4c78-8eef-d0dc76ad9cc6)

Happy coding!
