### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by Diegobalay1** [google-developer-training/basic-android-kotlin-compose-training-unscramble#7]
En el paso 7 del codelab, dentro de la **condición if** de la función **checkUserGuess()**. En codelab se escribe esto `if (_uiState.value.userGuess.equals(currentWord, true))`, y en realidad debería quedar así `if (userGuess.equals(currentWord, true))`.
Mi función al final del Codelab queda así, para también incrementar palabra intentada a la hora de un fallo:
```
 /*
     * Checks if the user's guess is correct.
     * Increases the score accordingly.
     */
    fun checkUserGuess() {
        if (userGuess != "") {
            if (userGuess.equals(currentWord, ignoreCase = true)) {
                val updatedScore = _uiState.value.score.plus(SCORE_INCREASE)
                updateGameState(updatedScore)
            } else {
                // User's guess is wrong, show an error
                if (usedWords.size < MAX_NO_OF_WORDS) {
                    _uiState.update { currentGameUiState ->
                        currentGameUiState.copy(
                            isGuessedWordWrong = true,
                            currentWordCount = currentGameUiState.currentWordCount.inc()
                        )
                    }
                    usedWords.add(userGuess)
                } else {
                    lastRound()
                }
            }
            // Reset user guess
            updateUserGuess("")
        }
    }
```
Edito. También hay que actualizar dentro del else el estado de la actualización del juego. `updateGameState(_uiState.value.score)`
Edito2. Solucionado. Subido proyecto también a Github. Rama newfun - [Unscramble Github](https://github.com/Diegobalay1/Unscramble/tree/newfun)

**Comment by Diegobalay1** [comment]
También comentar que al hacer esto hay que corregir también las palabras intentadas por otro lado, porque al final puede sobrepasar esos 10 intentos permitidos.

**Comment by osuleymanova** [comment]
Hola @Diegobalay1,

Gracias por contactarnos. El contenido de codelab está actualizado, consulte la captura de pantalla a continuación:

![Screen Shot 2022-12-14 at 2 51 00 PM](https://user-images.githubusercontent.com/86437155/207732340-5158a732-288e-467a-b5b5-f42f5a41e0b7.png)


Hello @Diegobalay1,

Thanks for reaching out to us. The codelab content is updated, please refer to the screenshot attached.
