### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by danikuzn** [google-developer-training/basic-android-kotlin-compose-training-unscramble#74]
"Open build.gradle(Module: Unscramble)" Should be changed for "Open build.gradle(Module: app)"

https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#4

**Comment by osuleymanova** [comment]
Hello @danikuzn,

Thank you for reaching out to us. The typo is fixed and will be published soon.
