### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by UjjwalT1** [google-developer-training/basic-android-kotlin-compose-training-unscramble#75]
![image](https://user-images.githubusercontent.com/121283901/226124586-5e2de2a4-749c-446e-afec-6a6eecec0616.png)

In Above Image the initialisation value of "val currentWordCount" and "val score" is 0 and 1 respectively, which is opposite of what actually should be. Below is what I feel right.
![image](https://user-images.githubusercontent.com/121283901/226125485-1086f33f-606c-49e5-a13a-f6a79ef13875.png)

**Comment by osuleymanova** [comment]
Hello @UjjwalT1,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/bf239f8d-d29a-42fe-98bc-3428e69d73b1)
