### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by lixoten** [google-developer-training/basic-android-kotlin-compose-training-unscramble#8]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-test-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-test-viewmodel#5

**In which task and step of the codelab can this issue be found?**
All  of them, Try running code solution.. won't work

**Describe the problem**
Can't run with coverage

**Steps to reproduce?**
Download solution and try running it with coverage

**Versions**
_Android Studio version:_ 
Android Studio Dolphin | 2021.3.1 Patch 1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Ussssntitled](https://user-images.githubusercontent.com/52259786/197376802-485695f1-fbf2-4196-a896-56844a636df2.png)

**Comment by osuleymanova** [comment]
Hello @lixoten,

Thanks for reaching out to us and sharing your concern.
Please provide the screenshot of the code in GameScreen.kt file so that we could help you with the troubleshooting:
 
![Screen Shot 2022-12-09 at 4 30 57 PM](https://user-images.githubusercontent.com/86437155/206818909-63672af8-fd52-4975-bdd8-13b7e654037d.png)

**Comment by lixoten** [comment]
> so that we could

![image](https://user-images.githubusercontent.com/52259786/210004510-447587b1-553d-450c-ba9e-accbfdc5a609.png)
![image](https://user-images.githubusercontent.com/52259786/210004539-71da8adf-79ac-416c-b980-534b05ed7d7a.png)

**Comment by lixoten** [comment]
By the way, they above only happens if you run the test with Coverage and after you click "Recompile"
![image](https://user-images.githubusercontent.com/52259786/210007383-0641f300-d1e2-4e74-bd16-678b25128e39.png)

**Comment by AAB999** [comment]
I have the same problem...either "recompile" and have all the errors or "no coverage"... is there an solution somewhere?

**Comment by osuleymanova** [comment]
Hello @lixoten,

Thank you for sharing the screenshots.
Please be sure to import:

<img width="680" alt="Screenshot 2023-04-07 at 12 16 20 PM" src="https://user-images.githubusercontent.com/86437155/230665301-c9553656-7587-4563-8c32-7d4eaee469f5.png">

and update all marked as "Kotlin: Unresolved reference: string" lines:

<img width="1059" alt="Screenshot 2023-04-07 at 12 13 09 PM" src="https://user-images.githubusercontent.com/86437155/230665570-85cb6e13-5af5-46c1-a241-c255ef0a923c.png">

If that doesn't help, please feel free to open a new ticket.
Happy Android learning!
