### ISSUE TITLE
Android Basics: Viewmodel and State in Compose. Course text issue

### ISSUE THREAD

**Issue by jderijke** [google-developer-training/basic-android-kotlin-compose-training-unscramble#90]
This is an issue on the course text, not on the code. I hope this is the correct way of sumitting as the contributing guidelines do not say anything on the course content.

[In step 5 Add a View Model ](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#4)
  Section Display random scrambled word
     item 3 (declare currentWord) should come before item 2, where it is used

alternatively the text at the end could say
current text: Android studio flags an error for the undefined function
corrected   : Android studio flags an error for the undefined variable and function

**Comment by osuleymanova** [comment]
Hello @jderijke,

Thank you for reaching out to us and sharing your feedback. The text will be updated and published.
