### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by koraysels** [google-developer-training/basic-android-kotlin-compose-training-unscramble#92]
```
Next, similar to the updates for the score, you need to update the word count.

Add another variable for the count in the GameUiState. Call it currentWordCount and initialize it to 1.

data class GameUiState(
   val currentScrambledWord: String = "",
   val currentWordCount: Int = 0,
   val score: Int = 1,
   val isGuessedWordWrong: Boolean = false,
)
```
[link to hightlight](https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-viewmodel-and-state#7:~:text=Next%2C%20similar%20to,to%201.)

initialize it to 1 but the wrong value is initialized to 1 ;)

**Comment by osuleymanova** [comment]
Hello @koraysels,

Thank you for reaching out to us and reporting this typo. The code snippet is updated:

![Screenshot 2023-05-31 at 4 14 51 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/3fa24037-4189-4675-9a11-0a93d2035a43)
