### ISSUE TITLE
Android Basics: Viewmodel and State in Compose

### ISSUE THREAD

**Issue by kcq888** [google-developer-training/basic-android-kotlin-compose-training-unscramble#93]
In step 8 of the codelab step #5, this text says that the currentWordCount should be 1, but the code snippest showed that it is intialized to 0. I had to set the currentWordCount to 1 and the score to 0.

**Comment by osuleymanova** [comment]
Hello @kcq888, 

Thank you for reaching out to us and reporting this typo. The code snippet is updated:
![Screenshot 2023-07-13 at 4 29 11 PM](https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/86437155/7c0c6cc3-acf9-4c00-ad17-04caec208dd0)
